export const SET_AUTH = 'SET_AUTH'
export const UPDATE_USER = 'UPDATE_USER'
export const ADD_USER = 'ADD_USER'
export const ALL_USER = 'ALL_USER'
export const LOGOUT = 'LOGOUT_USER'
export const CREATE_USER = 'CREATE_USER'

export const ADD_TABLE = 'ADD_TABLE'
export const UPDATE_TABLE = 'UPDATE_TABLE'
export const REMOVE_TABLE = 'REMOVE_TABLE'
export const ALL_TABLES = 'ALL_TABLES'

export const ADD_WORKPLACE = 'ADD_WORKPLACE'
export const UPDATE_WORKPLACE = 'UPDATE_WORKPLACE'
export const REMOVE_WORKPLACE = 'REMOVE_WORKPLACE'
export const ALL_WORKPLACES = 'ALL_WORKPLACES'

export const ADD_CARD = 'ADD_CARD'
export const ADD_CARD_CSV = 'ADD_CARD_CSV'
export const UPDATE_CARD = 'UPDATE_CARD'
export const REMOVE_CARD = 'REMOVE_CARD'
export const ALL_CARDS = 'ALL_CARDS'

export const ADD_COMMENT = 'ADD_COMMENT'
export const UPDATE_COMMENT = 'UPDATE_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const ALL_COMMENTS = 'ALL_COMMENTS'

export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const REMOVE_TASK = 'REMOVE_TASK'
export const ALL_TASKS = 'ALL_TASKS'

export const ADD_MESSAGER = 'ADD_MESSAGER'
export const UPDATE_MESSAGER = 'UPDATE_MESSAGER'
export const REMOVE_MESSAGER = 'REMOVE_MESSAGER'
export const ALL_MESSAGERS = 'ALL_MESSAGERS'
